import config
import dab.app_telemetry
import dab.device
import dab.health_check
import dab.input
import dab.operations
import dab.device_telemetry
import dab.voice
import dab.applications
import dab.system
import dab.output
import dab.version
from util.enforcement_manager import EnforcementManager

# Implement the test cases for conformance test.
CONFORMANCE_TEST_CASE = [
    ("operations/list",'{}', dab.operations.list, 200, "Conformance", False),
    ("applications/list",'{}', dab.applications.list, 250, "Conformance", False),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "Conformance", False),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "app launch Negative Test", True),
    ("applications/launch",'{{"appId_": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "Conformance Bad Request 1", True),
    ("applications/launch",'{{"appId": "invalid"}}', dab.applications.launch, 10000, "Conformance Bad Request 2", True),
    ("applications/launch",'{{"appId": true}}', dab.applications.launch, 10000, "Conformance Bad Request 3", True),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}", "parameters": ["v%3DSs75O8yllyc","enableEventConsole%3Dtrue","env_showConsole%3Dtrue"]}}', dab.applications.launch, 10000, "with parameters", False),
    ("applications/launch",'{{"appId": "{config.apps["youtube"]}", "parameters_": ["v%3DSs75O8yllyc","enableEventConsole%3Dtrue","env_showConsole%3Dtrue"]}}', dab.applications.launch, 10000, "with parameters bad request 1", True),
    ("applications/launch",'{{"appId": "{config.apps["youtube"]}", "parameters": true}}', dab.applications.launch, 10000, "with parameters bad request 2", True),
    ("applications/launch-with-content",f'{{"appId": "{config.apps["youtube"]}", "contentId": "jfKfPfyJRdk"}}', dab.applications.launch_with_content, 10000, "Conformance", False),
    ("applications/get-state",f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.get_state, 200, "Conformance", False),
    ("applications/exit",f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.exit, 5000, "Conformance", False),
    ("device/info",'{}', dab.device.info, 200, "Conformance", False),
    ("system/settings/list",'{}', dab.system.list, 200, "Conformance", False),
    ("system/settings/get",'{}', dab.system.get, 200, "Conformance", False),
    ("system/settings/set",'{"language": "en-US"}', dab.system.set, 120000, "language", False),
    ("system/settings/set",'{"language_": "en-US"}', dab.system.set, 120000, "language bad request1", True),
    ("system/settings/set",'{"language": true}', dab.system.set, 120000, "language bad request2", True),
    ("system/settings/set",'{"outputResolution": {"width": 3840, "height": 2160, "frequency": 60} }', dab.system.set, 3000, "outputResolution", False),
    ("system/settings/set",'{"outputResolution": "invalid" }', dab.system.set, 3000, "outputResolution bad request", True),
    ("system/settings/set",'{"memc": true}', dab.system.set, 3000, "memc", False),
    ("system/settings/set",'{"memc": "invalid"}', dab.system.set, 3000, "memc bad request", True),
    ("system/settings/set",'{"cec": true}', dab.system.set, 3000, "cec", False),
    ("system/settings/set",'{"cec": "invalid"}', dab.system.set, 3000, "cec bad request", True),
    ("system/settings/set",'{"lowLatencyMode": true}', dab.system.set, 3000, "lowLatencyMode", False),
    ("system/settings/set",'{"lowLatencyMode": "invalid"}', dab.system.set, 3000, "lowLatencyMode Bad Request", True),
    ("system/settings/set",'{"matchContentFrameRate": "EnabledSeamlessOnly"}', dab.system.set, 3000, "matchContentFrameRate", False),
    ("system/settings/set",'{"matchContentFrameRate": "invalid"}', dab.system.set, 3000, "matchContentFrameRate Bad Request", True),
    ("system/settings/set",'{"hdrOutputMode": "AlwaysHdr"}', dab.system.set, 3000, "hdrOutputMode", False),
    ("system/settings/set",'{"hdrOutputMode": "invalid"}', dab.system.set, 3000, "hdrOutputMode Bad Request", True),
    ("system/settings/set",'{"pictureMode": "Standard"}', dab.system.set, 3000, "pictureMode", False),
    ("system/settings/set",'{"pictureMode": "invalid"}', dab.system.set, 3000, "pictureMode Bad Request", True),
    ("system/settings/set",'{"audioOutputMode": "Auto"}', dab.system.set, 3000, "audioOutputMode", False),
    ("system/settings/set",'{"audioOutputMode": "invalid"}', dab.system.set, 3000, "audioOutputMode Bad Request", True),
    ("system/settings/set",'{"audioOutputSource": "HDMI"}', dab.system.set, 3000, "audioOutputSource", False),
    ("system/settings/set",'{"audioOutputSource": "invalid"}', dab.system.set, 3000, "audioOutputSource Bad Request", True),
    ("system/settings/set",'{"videoInputSource": "HDMI1"}', dab.system.set, 3000, "videoInputSource", False),
    ("system/settings/set",'{"videoInputSource": "invalid"}', dab.system.set, 3000, "videoInputSource Bad Request", True),
    ("system/settings/set",'{"audioVolume": 10}', dab.system.set, 3000, "audioVolume", False),
    ("system/settings/set",'{"audioVolume": 120}', dab.system.set, 3000, "audioVolume - Negative Test", True),
    ("system/settings/set",'{"audioVolume": true}', dab.system.set, 3000, "audioVolume bad request", True),
    ("system/settings/set",'{"mute": false}', dab.system.set, 3000, "mute", False),
    ("system/settings/set",'{"mute": "invalid"}', dab.system.set, 3000, "mute bad request", True),
    ("system/settings/set",'{"textToSpeech": true}', dab.system.set, 3000, "textToSpeech", False),
    ("system/settings/set",'{"textToSpeech": "invalid"}', dab.system.set, 3000, "textToSpeech bad request", True),
    ("input/key/list",'{}', dab.input.list, 200, "Conformance", False),
    ("input/key-press",'{"keyCode": "KEY_HOME"}', dab.input.key_press, 1000, "KEY_HOME", False),
    ("input/key-press",'{"keyCode": "KEY_VOLUME_UP"}', dab.input.key_press, 1000, "KEY_VOLUME_UP", False),
    ("input/key-press",'{"keyCode": "KEY_VOLUME_DOWN"}', dab.input.key_press, 1000, "KEY_VOLUME_DOWN", False),
    ("input/key-press",'{"keyCode": "KEY_MUTE"}', dab.input.key_press, 1000, "KEY_MUTE", False),
    ("input/key-press",'{"keyCode": "dummy"}', dab.input.key_press, 1000, "dummy", True),
    ("input/key-press",'{"keyCode": ""}', dab.input.key_press, 1000, "null", True),
    ("input/key-press",'{"keyCode": "KEY_CHANNEL_UP"}', dab.input.key_press, 1000, "KEY_CHANNEL_UP", False),
    ("input/key-press",'{"keyCode": "KEY_CHANNEL_DOWN"}', dab.input.key_press, 1000, "KEY_CHANNEL_DOWN", False),
    ("input/key-press",'{"keyCode": "KEY_MENU"}', dab.input.key_press, 1000, "KEY_MENU", False),
    ("input/key-press",'{"keyCode": "KEY_EXIT"}', dab.input.key_press, 1000, "KEY_EXIT", False),
    ("input/key-press",'{"keyCode": "KEY_INFO"}', dab.input.key_press, 1000, "KEY_INFO", False),
    ("input/key-press",'{"keyCode": "KEY_GUIDE"}', dab.input.key_press, 1000, "KEY_GUIDE", False),
    ("input/key-press",'{"keyCode": "KEY_CAPTIONS"}', dab.input.key_press, 1000, "KEY_CAPTIONS", False),
    ("input/key-press",'{"keyCode": "KEY_UP"}', dab.input.key_press, 1000, "KEY_UP", False),
    ("input/key-press",'{"keyCode": "KEY_PAGE_UP"}', dab.input.key_press, 1000, "KEY_PAGE_UP", False),
    ("input/key-press",'{"keyCode": "KEY_PAGE_DOWN"}', dab.input.key_press, 1000, "KEY_PAGE_DOWN", False),
    ("input/key-press",'{"keyCode": "KEY_RIGHT"}', dab.input.key_press, 1000, "KEY_RIGHT", False),
    ("input/key-press",'{"keyCode": "KEY_DOWN"}', dab.input.key_press, 1000, "KEY_DOWN", False),
    ("input/key-press",'{"keyCode": "KEY_LEFT"}', dab.input.key_press, 1000, "KEY_LEFT", False),
    ("input/key-press",'{"keyCode": "KEY_ENTER"}', dab.input.key_press, 1000, "KEY_ENTER", False),
    ("input/key-press",'{"keyCode": "KEY_BACK"}', dab.input.key_press, 1000, "KEY_BACK", False),
    ("input/key-press",'{"keyCode": "KEY_PLAY"}', dab.input.key_press, 1000, "KEY_PLAY", False),
    ("input/key-press",'{"keyCode": "KEY_PLAY_PAUSE"}', dab.input.key_press, 1000, "KEY_PLAY_PAUSE", False),
    ("input/key-press",'{"keyCode": "KEY_PAUSE"}', dab.input.key_press, 1000, "KEY_PAUSE", False),
    ("input/key-press",'{"keyCode": "KEY_STOP"}', dab.input.key_press, 1000, "KEY_STOP", False),
    ("input/key-press",'{"keyCode": "KEY_REWIND"}', dab.input.key_press, 1000, "KEY_REWIND", False),
    ("input/key-press",'{"keyCode": "KEY_FAST_FORWARD"}', dab.input.key_press, 1000, "KEY_FAST_FORWARD", False),
    ("input/key-press",'{"keyCode": "KEY_SKIP_REWIND"}', dab.input.key_press, 1000, "KEY_SKIP_REWIND", False),
    ("input/key-press",'{"keyCode": "KEY_SKIP_FAST_FORWARD"}', dab.input.key_press, 1000, "KEY_SKIP_FAST_FORWARD", False),
    ("input/key-press",'{"keyCode": "KEY_0"}', dab.input.key_press, 1000, "KEY_0", False),
    ("input/key-press",'{"keyCode": "KEY_1"}', dab.input.key_press, 1000, "KEY_1", False),
    ("input/key-press",'{"keyCode": "KEY_2"}', dab.input.key_press, 1000, "KEY_2", False),
    ("input/key-press",'{"keyCode": "KEY_3"}', dab.input.key_press, 1000, "KEY_3", False),
    ("input/key-press",'{"keyCode": "KEY_4"}', dab.input.key_press, 1000, "KEY_4", False),
    ("input/key-press",'{"keyCode": "KEY_5"}', dab.input.key_press, 1000, "KEY_5", False),
    ("input/key-press",'{"keyCode": "KEY_6"}', dab.input.key_press, 1000, "KEY_6", False),
    ("input/key-press",'{"keyCode": "KEY_7"}', dab.input.key_press, 1000, "KEY_7", False),
    ("input/key-press",'{"keyCode": "KEY_8"}', dab.input.key_press, 1000, "KEY_8", False),
    ("input/key-press",'{"keyCode": "KEY_9"}', dab.input.key_press, 1000, "KEY_9", False),
    ("input/key-press",'{"keyCode_": "KEY_HOME"}', dab.input.key_press, 1000, "KEY_HOME Bad Request1", True),
    ("input/key-press",'{"keyCode": "invalid"}', dab.input.key_press, 1000, "KEY_HOME Bad Request2", True),
    ("input/key-press",'{"keyCode": true}', dab.input.key_press, 1000, "KEY_HOME Bad Request3", True),
    ("input/long-key-press",'{"keyCode": "KEY_HOME", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_HOME", False),
    ("input/long-key-press",'{"keyCode": "KEY_VOLUME_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_VOLUME_UP", False),
    ("input/long-key-press",'{"keyCode": "KEY_VOLUME_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_VOLUME_DOWN", False),
    ("input/long-key-press",'{"keyCode": "KEY_MUTE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_MUTE", False),
    ("input/long-key-press",'{"keyCode": "KEY_CHANNEL_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CHANNEL_UP", False),
    ("input/long-key-press",'{"keyCode": "KEY_CHANNEL_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CHANNEL_DOWN", False),
    ("input/long-key-press",'{"keyCode": "KEY_MENU", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_MENU", False),
    ("input/long-key-press",'{"keyCode": "KEY_EXIT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_EXIT", False),
    ("input/long-key-press",'{"keyCode": "KEY_INFO", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_INFO", False),
    ("input/long-key-press",'{"keyCode": "KEY_GUIDE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_GUIDE", False),
    ("input/long-key-press",'{"keyCode": "KEY_CAPTIONS", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CAPTIONS", False),
    ("input/long-key-press",'{"keyCode": "KEY_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_UP", False),
    ("input/long-key-press",'{"keyCode": "KEY_PAGE_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAGE_UP", False),
    ("input/long-key-press",'{"keyCode": "KEY_PAGE_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAGE_DOWN", False),
    ("input/long-key-press",'{"keyCode": "KEY_RIGHT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_RIGHT", False),
    ("input/long-key-press",'{"keyCode": "KEY_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_DOWN", False),
    ("input/long-key-press",'{"keyCode": "KEY_LEFT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_LEFT", False),
    ("input/long-key-press",'{"keyCode": "KEY_ENTER", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_ENTER", False),
    ("input/long-key-press",'{"keyCode": "KEY_BACK", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_BACK", False),
    ("input/long-key-press",'{"keyCode": "KEY_PLAY", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PLAY", False),
    ("input/long-key-press",'{"keyCode": "KEY_PLAY_PAUSE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PLAY_PAUSE", False),
    ("input/long-key-press",'{"keyCode": "KEY_PAUSE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAUSE", False),
    ("input/long-key-press",'{"keyCode": "KEY_STOP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_STOP", False),
    ("input/long-key-press",'{"keyCode": "KEY_REWIND", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_REWIND", False),
    ("input/long-key-press",'{"keyCode": "KEY_FAST_FORWARD", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_FAST_FORWARD", False),
    ("input/long-key-press",'{"keyCode": "KEY_SKIP_REWIND", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_SKIP_REWIND", False),
    ("input/long-key-press",'{"keyCode": "KEY_SKIP_FAST_FORWARD", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_SKIP_FAST_FORWARD", False),
    ("input/long-key-press",'{"keyCode": "KEY_0", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_0", False),
    ("input/long-key-press",'{"keyCode": "KEY_1", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_1", False),
    ("input/long-key-press",'{"keyCode": "KEY_2", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_2", False),
    ("input/long-key-press",'{"keyCode": "KEY_3", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_3", False),
    ("input/long-key-press",'{"keyCode": "KEY_4", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_4", False),
    ("input/long-key-press",'{"keyCode": "KEY_5", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_5", False),
    ("input/long-key-press",'{"keyCode": "KEY_6", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_6", False),
    ("input/long-key-press",'{"keyCode": "KEY_7", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_7", False),
    ("input/long-key-press",'{"keyCode": "KEY_8", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_8", False),
    ("input/long-key-press",'{"keyCode": "KEY_9", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_9", False),
    ("output/image",'{}', dab.output.image, 2000, "Conformance", False),
    ("device-telemetry/start",'{"duration": 1000}', dab.device_telemetry.start, 200, "Conformance", False),
    ("device-telemetry/stop",'{}', dab.device_telemetry.stop, 200, "Conformance", False),
    ("app-telemetry/start",lambda: f'{{"appId": "{config.apps["youtube"]}", "duration": 1000}}', dab.app_telemetry.start, 700, "Conformance", False),
    ("app-telemetry/stop",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.app_telemetry.stop, 200, "Conformance", False),
    ("health-check/get",'{}', dab.health_check.get, 2000, "Conformance", False),
    ("voice/list",'{}', dab.voice.list, 200, "Conformance", False),
    ("voice/set",f'{{"voiceSystem":{{"name":"{config.va}","enabled":true}}}}', dab.voice.set, 5000, "Conformance", False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/ladygaga.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance", False),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA", False),
    ("voice/send-text",f'{{"requestText_" : "Play lady Gaga music on YouTube", "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request1", True),
    ("voice/send-text",f'{{"requestText" : true, "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request2", True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem_": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request3", True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": "invalid"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request4", True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": true}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request5", True),
    ("version",' {}', dab.version.default, 200, "Conformance", False),
    ("system/restart",' {}', dab.system.restart, 30000, "Conformance", False),
    ("applications/install", f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/applications/myfile.apk"}}', dab.applications.install, 120000, "Install App Conformance", False),
    ("applications/uninstall",lambda: f'{{"appId": "{config.apps["sample_app"]}"}}', dab.applications.uninstall, 50000, "Conformance", False),
    ("applications/clear-data",lambda: f'{{"appId": "{config.apps["sample_app"]}"}}', dab.applications.clear_data, 10000, "Conformance", False),
    ("applications/install-from-app-store", f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/applications/myfile.apk"}}', dab.applications.install_from_appstore, 120000, "Install App Conformance", False),
]
