import config
import dab.app_telemetry
import dab.device
import dab.health_check
import dab.input
import dab.operations
import dab.device_telemetry
import dab.voice
import dab.applications
import dab.system
import dab.output
import dab.version
import json
from util.enforcement_manager import EnforcementManager
from util.config_loader import ensure_app_available
from util.config_loader import get_or_prompt_appstore_url
import dab_version as ver

# Implement the test cases for conformance test.
CONFORMANCE_TEST_CASE = [
    ("operations/list",'{}', dab.operations.list, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("applications/list",'{}', dab.applications.list, 250, "Conformance", ver.DABVersion.V2_0, False),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "Conformance", ver.DABVersion.V2_0, False),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "app launch Negative Test", ver.DABVersion.V2_0, True),
    ("applications/launch",f'{{"appId_": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "Conformance Bad Request 1", ver.DABVersion.V2_0, True),
    ("applications/launch",'{"appId": "invalid"}', dab.applications.launch, 10000, "Conformance Bad Request 2", ver.DABVersion.V2_0, True),
    ("applications/launch",'{"appId": true}', dab.applications.launch, 10000, "Conformance Bad Request 3", ver.DABVersion.V2_0, True),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}", "parameters": ["v%3DSs75O8yllyc","enableEventConsole%3Dtrue","env_showConsole%3Dtrue"]}}', dab.applications.launch, 10000, "with parameters", ver.DABVersion.V2_0, False),
    ("applications/launch",f'{{"appId": "{config.apps["youtube"]}", "parameters_": ["v%3DSs75O8yllyc","enableEventConsole%3Dtrue","env_showConsole%3Dtrue"]}}', dab.applications.launch, 10000, "with parameters bad request 1", ver.DABVersion.V2_0, True),
    ("applications/launch",f'{{"appId": "{config.apps["youtube"]}", "parameters": true}}', dab.applications.launch, 10000, "with parameters bad request 2", ver.DABVersion.V2_0, True),
    ("applications/launch-with-content",f'{{"appId": "{config.apps["youtube"]}", "contentId": "jfKfPfyJRdk"}}', dab.applications.launch_with_content, 10000, "Conformance", ver.DABVersion.V2_0, False),
    ("applications/launch-with-content",f'{{"appId": "{config.apps["youtube"]}", "contentId": "invalid_id"}}', dab.applications.launch_with_content, 10000, "Conformance invalid content", ver.DABVersion.V2_0, True),
    ("applications/get-state",f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.get_state, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("applications/exit",f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.exit, 5000, "Conformance", ver.DABVersion.V2_0, False),
    ("device/info",'{}', dab.device.info, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("system/settings/list",'{}', dab.system.settings_list, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("system/settings/get",'{}', dab.system.settings_get, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"language": "en-US"}', dab.system.settings_set, 120000, "language", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"language_": "en-US"}', dab.system.settings_set, 120000, "language bad request1", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"language": true}', dab.system.settings_set, 120000, "language bad request2", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"outputResolution": {"width": 3840, "height": 2160, "frequency": 60} }', dab.system.settings_set, 3000, "outputResolution", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"outputResolution": "invalid" }', dab.system.settings_set, 3000, "outputResolution bad request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"memc": true}', dab.system.settings_set, 3000, "memc", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"memc": "invalid"}', dab.system.settings_set, 3000, "memc bad request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"cec": true}', dab.system.settings_set, 3000, "cec", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"cec": "invalid"}', dab.system.settings_set, 3000, "cec bad request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"lowLatencyMode": true}', dab.system.settings_set, 3000, "lowLatencyMode", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"lowLatencyMode": "invalid"}', dab.system.settings_set, 3000, "lowLatencyMode Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"matchContentFrameRate": "EnabledSeamlessOnly"}', dab.system.settings_set, 3000, "matchContentFrameRate", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"matchContentFrameRate": "invalid"}', dab.system.settings_set, 3000, "matchContentFrameRate Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"hdrOutputMode": "AlwaysHdr"}', dab.system.settings_set, 3000, "hdrOutputMode", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"hdrOutputMode": "invalid"}', dab.system.settings_set, 3000, "hdrOutputMode Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"pictureMode": "Standard"}', dab.system.settings_set, 3000, "pictureMode", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"pictureMode": "invalid"}', dab.system.settings_set, 3000, "pictureMode Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"audioOutputMode": "Auto"}', dab.system.settings_set, 3000, "audioOutputMode", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"audioOutputMode": "invalid"}', dab.system.settings_set, 3000, "audioOutputMode Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"audioOutputSource": "HDMI"}', dab.system.settings_set, 3000, "audioOutputSource", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"audioOutputSource": "invalid"}', dab.system.settings_set, 3000, "audioOutputSource Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"videoInputSource": "HDMI1"}', dab.system.settings_set, 3000, "videoInputSource", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"videoInputSource": "invalid"}', dab.system.settings_set, 3000, "videoInputSource Bad Request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"audioVolume": 10}', dab.system.settings_set, 3000, "audioVolume", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"audioVolume": 120}', dab.system.settings_set, 3000, "audioVolume - Negative Test", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"audioVolume": true}', dab.system.settings_set, 3000, "audioVolume bad request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"mute": false}', dab.system.settings_set, 3000, "mute", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"mute": "invalid"}', dab.system.settings_set, 3000, "mute bad request", ver.DABVersion.V2_0, True),
    ("system/settings/set",'{"textToSpeech": true}', dab.system.settings_set, 3000, "textToSpeech", ver.DABVersion.V2_0, False),
    ("system/settings/set",'{"textToSpeech": "invalid"}', dab.system.settings_set, 3000, "textToSpeech bad request", ver.DABVersion.V2_0, True),
    ("system/settings/set", '{"screenSaver": true}', dab.system.settings_set, 5000, "Set Screen Saver", ver.DABVersion.V2_1, False),
    ("system/settings/set", '{"screenSaverTimeout": 300}', dab.system.settings_set, 5000, "Set Screen Saver Timeout", ver.DABVersion.V2_1, False ),
    ("system/settings/set", '{"screenSaverMinTimeout": 60}', dab.system.settings_set, 5000, "Set Screen Saver Min Timeout", ver.DABVersion.V2_1, False),
    ("system/settings/set", '{"personalizedAds": true}', dab.system.settings_set, 5000, "Set Personalized Ads", ver.DABVersion.V2_1 , False),
    ("system/settings/set", '{"highContrastText": true}', dab.system.settings_set, 5000, "Set High Contrast Text", ver.DABVersion.V2_1 , False),
    ("system/settings/set", '{"identifierForAdvertising": true}', dab.system.settings_set, 5000, "Set identifier For Advertising", ver.DABVersion.V2_1 , False),
    ("system/settings/set", '{"brightness": 10}', dab.system.settings_set, 5000, "Set brightness", ver.DABVersion.V2_1 , False),
    ("system/settings/set", '{"contrast": 10}', dab.system.settings_set, 5000, "Set contrast", ver.DABVersion.V2_1 , False),
    ("system/settings/set", '{"timeZone": "America/Los_Angeles"}', dab.system.settings_set, 5000, "Set timeZone", ver.DABVersion.V2_1 , False),
    ("input/key/list",'{}', dab.input.list, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_HOME"}', dab.input.key_press, 1000, "KEY_HOME", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_VOLUME_UP"}', dab.input.key_press, 1000, "KEY_VOLUME_UP", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_VOLUME_DOWN"}', dab.input.key_press, 1000, "KEY_VOLUME_DOWN", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_MUTE"}', dab.input.key_press, 1000, "KEY_MUTE", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "dummy"}', dab.input.key_press, 1000, "dummy", ver.DABVersion.V2_0, True),
    ("input/key-press",'{"keyCode": ""}', dab.input.key_press, 1000, "null", ver.DABVersion.V2_0, True),
    ("input/key-press",'{"keyCode": "KEY_CHANNEL_UP"}', dab.input.key_press, 1000, "KEY_CHANNEL_UP", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_CHANNEL_DOWN"}', dab.input.key_press, 1000, "KEY_CHANNEL_DOWN", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_MENU"}', dab.input.key_press, 1000, "KEY_MENU", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_EXIT"}', dab.input.key_press, 1000, "KEY_EXIT", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_INFO"}', dab.input.key_press, 1000, "KEY_INFO", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_GUIDE"}', dab.input.key_press, 1000, "KEY_GUIDE", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_CAPTIONS"}', dab.input.key_press, 1000, "KEY_CAPTIONS", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_UP"}', dab.input.key_press, 1000, "KEY_UP", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_PAGE_UP"}', dab.input.key_press, 1000, "KEY_PAGE_UP", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_PAGE_DOWN"}', dab.input.key_press, 1000, "KEY_PAGE_DOWN", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_RIGHT"}', dab.input.key_press, 1000, "KEY_RIGHT", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_DOWN"}', dab.input.key_press, 1000, "KEY_DOWN", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_LEFT"}', dab.input.key_press, 1000, "KEY_LEFT", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_ENTER"}', dab.input.key_press, 1000, "KEY_ENTER", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_BACK"}', dab.input.key_press, 1000, "KEY_BACK", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_PLAY"}', dab.input.key_press, 1000, "KEY_PLAY", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_PLAY_PAUSE"}', dab.input.key_press, 1000, "KEY_PLAY_PAUSE", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_PAUSE"}', dab.input.key_press, 1000, "KEY_PAUSE", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_STOP"}', dab.input.key_press, 1000, "KEY_STOP", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_REWIND"}', dab.input.key_press, 1000, "KEY_REWIND", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_FAST_FORWARD"}', dab.input.key_press, 1000, "KEY_FAST_FORWARD", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_SKIP_REWIND"}', dab.input.key_press, 1000, "KEY_SKIP_REWIND", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_SKIP_FAST_FORWARD"}', dab.input.key_press, 1000, "KEY_SKIP_FAST_FORWARD", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_0"}', dab.input.key_press, 1000, "KEY_0", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_1"}', dab.input.key_press, 1000, "KEY_1", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_2"}', dab.input.key_press, 1000, "KEY_2", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_3"}', dab.input.key_press, 1000, "KEY_3", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_4"}', dab.input.key_press, 1000, "KEY_4", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_5"}', dab.input.key_press, 1000, "KEY_5", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_6"}', dab.input.key_press, 1000, "KEY_6", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_7"}', dab.input.key_press, 1000, "KEY_7", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_8"}', dab.input.key_press, 1000, "KEY_8", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode": "KEY_9"}', dab.input.key_press, 1000, "KEY_9", ver.DABVersion.V2_0, False),
    ("input/key-press", '{"keyCode": "KEY_RED"}', dab.input.key_press, 1000, "KEY_RED", ver.DABVersion.V2_0, False),
    ("input/key-press", '{"keyCode": "KEY_GREEN"}', dab.input.key_press, 1000, "KEY_GREEN", ver.DABVersion.V2_0, False),
    ("input/key-press", '{"keyCode": "KEY_YELLOW"}', dab.input.key_press, 1000, "KEY_YELLOW", ver.DABVersion.V2_0, False),
    ("input/key-press", '{"keyCode": "KEY_BLUE"}', dab.input.key_press, 1000, "KEY_BLUE", ver.DABVersion.V2_0, False),
    ("input/key-press", '{"keyCode": "KEY_YOUTUBE"}', dab.input.key_press, 1000, "KEY_YOUTUBE", ver.DABVersion.V2_0, False),
    ("input/key-press",'{"keyCode_": "KEY_HOME"}', dab.input.key_press, 1000, "KEY_HOME Bad Request1", ver.DABVersion.V2_0, True),
    ("input/key-press",'{"keyCode": "invalid"}', dab.input.key_press, 1000, "KEY_HOME Bad Request2", ver.DABVersion.V2_0, True),
    ("input/key-press",'{"keyCode": true}', dab.input.key_press, 1000, "KEY_HOME Bad Request3", ver.DABVersion.V2_0, True),
    ("input/long-key-press",'{"keyCode": "KEY_HOME", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_HOME", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_VOLUME_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_VOLUME_UP", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_VOLUME_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_VOLUME_DOWN", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_MUTE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_MUTE", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_CHANNEL_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CHANNEL_UP", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_CHANNEL_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CHANNEL_DOWN", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_MENU", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_MENU", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_EXIT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_EXIT", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_INFO", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_INFO", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_GUIDE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_GUIDE", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_CAPTIONS", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CAPTIONS", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_UP", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_PAGE_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAGE_UP", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_PAGE_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAGE_DOWN", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_RIGHT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_RIGHT", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_DOWN", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_LEFT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_LEFT", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_ENTER", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_ENTER", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_BACK", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_BACK", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_PLAY", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PLAY", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_PLAY_PAUSE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PLAY_PAUSE", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_PAUSE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAUSE", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_STOP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_STOP", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_REWIND", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_REWIND", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_FAST_FORWARD", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_FAST_FORWARD", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_SKIP_REWIND", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_SKIP_REWIND", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_SKIP_FAST_FORWARD", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_SKIP_FAST_FORWARD", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_0", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_0", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_1", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_1", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_2", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_2", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_3", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_3", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_4", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_4", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_5", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_5", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_6", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_6", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_7", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_7", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_8", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_8", ver.DABVersion.V2_0, False),
    ("input/long-key-press",'{"keyCode": "KEY_9", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_9", ver.DABVersion.V2_0, False),
    ("input/long-key-press", '{"keyCode": "KEY_RED", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_RED", ver.DABVersion.V2_0, False),
    ("input/long-key-press", '{"keyCode": "KEY_GREEN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_GREEN", ver.DABVersion.V2_0, False),
    ("input/long-key-press", '{"keyCode": "KEY_YELLOW", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_YELLOW", ver.DABVersion.V2_0, False),
    ("input/long-key-press", '{"keyCode": "KEY_BLUE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_BLUE", ver.DABVersion.V2_0, False),
    ("input/long-key-press", '{"keyCode": "KEY_YOUTUBE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_YOUTUBE", ver.DABVersion.V2_0, False),
    ("output/image",'{}', dab.output.image, 2000, "Conformance", ver.DABVersion.V2_0, False),
    ("device-telemetry/start",'{"duration": 1000}', dab.device_telemetry.start, 700, "Conformance", ver.DABVersion.V2_0, False),
    ("device-telemetry/stop",'{}', dab.device_telemetry.stop, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("app-telemetry/start",lambda: f'{{"appId": "{config.apps["youtube"]}", "duration": 1000}}', dab.app_telemetry.start, 700, "Conformance", ver.DABVersion.V2_0, False),
    ("app-telemetry/stop",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.app_telemetry.stop, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("health-check/get",'{}', dab.health_check.get, 2000, "Conformance", ver.DABVersion.V2_0, False),
    ("voice/list",'{}', dab.voice.list, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("voice/set",f'{{"voiceSystem":{{"name":"{config.va}","enabled":true}}}}', dab.voice.set, 5000, "Conformance", ver.DABVersion.V2_0, False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/ladygaga.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance", ver.DABVersion.V2_0, False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/OpenNetflix.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance Open Netflix", ver.DABVersion.V2_0, False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/OpenNetflix.mp4", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance With Unsupported Format", ver.DABVersion.V2_0, True),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/CorruptedAudio.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance With Corrupted Audio", ver.DABVersion.V2_0, True),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/KoreanAudio.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000,"Sending Different Language Audio", ver.DABVersion.V2_0,False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/LongAudioClip.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000,"Sending Long Audio Clip", ver.DABVersion.V2_0,False),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA", ver.DABVersion.V2_0, False),
    ("voice/send-text",f'{{"requestText_" : "Play lady Gaga music on YouTube", "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request1", ver.DABVersion.V2_0, True),
    ("voice/send-text",f'{{"requestText" : true, "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request2", ver.DABVersion.V2_0, True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem_": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request3", ver.DABVersion.V2_0, True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": "invalid"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request4", ver.DABVersion.V2_0, True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": true}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request5", ver.DABVersion.V2_0, True),
    ("version",' {}', dab.version.default, 200, "Conformance", ver.DABVersion.V2_0, False),
    ("system/restart",' {}', dab.system.restart, 30000, "Conformance", ver.DABVersion.V2_0, False),
    ("applications/install", lambda: json.dumps({"fileLocation": f"file://{ensure_app_available()}"}), dab.applications.install, 120000, "Install App Conformance", ver.DABVersion.V2_1, False), 
    ("applications/install", lambda: json.dumps({"fileLocation": f""}), dab.applications.install, 120000, "Install App Conformance With Blank URL", ver.DABVersion.V2_1, True),
    ("applications/install", lambda: json.dumps({"fileLocation": f"file://{ensure_app_available('unsupported_format_app.txt')}"}), dab.applications.install, 120000, "Install App Conformance With Incorrect Format", ver.DABVersion.V2_1, True),
    ("applications/uninstall",lambda: f'{{"appId": "{config.apps["sample_app"]}"}}', dab.applications.uninstall, 50000, "Conformance", ver.DABVersion.V2_1, False), 
    ("applications/clear-data",lambda: f'{{"app_url": "{config.apps["sample_app_url"]}"}}', dab.applications.clear_data, 10000, "Conformance", ver.DABVersion.V2_1, False), 
    ("applications/install-from-app-store", lambda: json.dumps({"appId": get_or_prompt_appstore_url()}), dab.applications.install_from_appstore, 120000, "Install App Conformance", ver.DABVersion.V2_1 , False),
    ("system/logs/start-collection", '{}', dab.system.start_log_collection, 200, "Conformance", ver.DABVersion.V2_1 , False), 
    ("system/logs/stop-collection", '{}', dab.system.stop_log_collection, 200, "Conformance", ver.DABVersion.V2_1 , False), 
    ("system/logs/stop-collection", '{}', dab.system.stop_log_collection, 400, "Stop Without Start Negative", ver.DABVersion.V2_1 , True),
    ("system/power-mode/get", '{}', dab.system.power_mode_get, 200, "Conformance", ver.DABVersion.V2_1 , False),
    ("system/power-mode/set", '{"powerMode": "Standby"}', dab.system.power_mode_set, 200, "Conformance", ver.DABVersion.V2_1 , False),
    ("system/setup/skip", '{}', dab.system.setup_skip, 1000, "Conformance", ver.DABVersion.V2_1 , False),
]
