import config
import dab.app_telemetry
import dab.device
import dab.health_check
import dab.input
import dab.operations
import dab.device_telemetry
import dab.voice
import dab.applications
import dab.system
import dab.output
import dab.version
import json
from util.enforcement_manager import EnforcementManager
from util.config_loader import ensure_app_available
from util.config_loader import get_or_prompt_appstore_url

# Implement the test cases for conformance test.
CONFORMANCE_TEST_CASE = [
    ("operations/list",'{}', dab.operations.list, 200, "Conformance", "2.0", False),
    ("applications/list",'{}', dab.applications.list, 250, "Conformance", "2.0", False),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "Conformance", "2.0", False),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "app launch Negative Test", "2.0", True),
    ("applications/launch",f'{{"appId_": "{config.apps["youtube"]}"}}', dab.applications.launch, 10000, "Conformance Bad Request 1", "2.0", True),
    ("applications/launch",'{"appId": "invalid"}', dab.applications.launch, 10000, "Conformance Bad Request 2", "2.0", True),
    ("applications/launch",'{"appId": true}', dab.applications.launch, 10000, "Conformance Bad Request 3", "2.0", True),
    ("applications/launch",lambda: f'{{"appId": "{config.apps["youtube"]}", "parameters": ["v%3DSs75O8yllyc","enableEventConsole%3Dtrue","env_showConsole%3Dtrue"]}}', dab.applications.launch, 10000, "with parameters", "2.0", False),
    ("applications/launch",f'{{"appId": "{config.apps["youtube"]}", "parameters_": ["v%3DSs75O8yllyc","enableEventConsole%3Dtrue","env_showConsole%3Dtrue"]}}', dab.applications.launch, 10000, "with parameters bad request 1", "2.0", True),
    ("applications/launch",f'{{"appId": "{config.apps["youtube"]}", "parameters": true}}', dab.applications.launch, 10000, "with parameters bad request 2", "2.0", True),
    ("applications/launch-with-content",f'{{"appId": "{config.apps["youtube"]}", "contentId": "jfKfPfyJRdk"}}', dab.applications.launch_with_content, 10000, "Conformance", "2.0", False),
    ("applications/launch-with-content",f'{{"appId": "{config.apps["youtube"]}", "contentId": "invalid_id"}}', dab.applications.launch_with_content, 10000, "Conformance invalid content", "2.0", True),
    ("applications/get-state",f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.get_state, 200, "Conformance", "2.0", False),
    ("applications/exit",f'{{"appId": "{config.apps["youtube"]}"}}', dab.applications.exit, 5000, "Conformance", "2.0", False),
    ("device/info",'{}', dab.device.info, 200, "Conformance", "2.0", False),
    ("system/settings/list",'{}', dab.system.settings_list, 200, "Conformance", "2.0", False),
    ("system/settings/get",'{}', dab.system.settings_get, 750, "Conformance", "2.0", False),
    ("system/settings/set",'{"language": "en-US"}', dab.system.settings_set, 120000, "language", "2.0", False),
    ("system/settings/set",'{"language_": "en-US"}', dab.system.settings_set, 120000, "language bad request1", "2.0", True),
    ("system/settings/set",'{"language": true}', dab.system.settings_set, 120000, "language bad request2", "2.0", True),
    ("system/settings/set",'{"outputResolution": {"width": 3840, "height": 2160, "frequency": 60} }', dab.system.settings_set, 3000, "outputResolution", "2.0", False),
    ("system/settings/set",'{"outputResolution": "invalid" }', dab.system.settings_set, 3000, "outputResolution bad request", "2.0", True),
    ("system/settings/set",'{"memc": true}', dab.system.settings_set, 3000, "memc", "2.0", False),
    ("system/settings/set",'{"memc": "invalid"}', dab.system.settings_set, 3000, "memc bad request", "2.0", True),
    ("system/settings/set",'{"cec": true}', dab.system.settings_set, 3000, "cec", "2.0", False),
    ("system/settings/set",'{"cec": "invalid"}', dab.system.settings_set, 3000, "cec bad request", "2.0", True),
    ("system/settings/set",'{"lowLatencyMode": true}', dab.system.settings_set, 3000, "lowLatencyMode", "2.0", False),
    ("system/settings/set",'{"lowLatencyMode": "invalid"}', dab.system.settings_set, 3000, "lowLatencyMode Bad Request", "2.0", True),
    ("system/settings/set",'{"matchContentFrameRate": "EnabledSeamlessOnly"}', dab.system.settings_set, 3000, "matchContentFrameRate", "2.0", False),
    ("system/settings/set",'{"matchContentFrameRate": "invalid"}', dab.system.settings_set, 3000, "matchContentFrameRate Bad Request", "2.0", True),
    ("system/settings/set",'{"hdrOutputMode": "AlwaysHdr"}', dab.system.settings_set, 3000, "hdrOutputMode", "2.0", False),
    ("system/settings/set",'{"hdrOutputMode": "invalid"}', dab.system.settings_set, 3000, "hdrOutputMode Bad Request", "2.0", True),
    ("system/settings/set",'{"pictureMode": "Standard"}', dab.system.settings_set, 3000, "pictureMode", "2.0", False),
    ("system/settings/set",'{"pictureMode": "invalid"}', dab.system.settings_set, 3000, "pictureMode Bad Request", "2.0", True),
    ("system/settings/set",'{"audioOutputMode": "Auto"}', dab.system.settings_set, 3000, "audioOutputMode", "2.0", False),
    ("system/settings/set",'{"audioOutputMode": "invalid"}', dab.system.settings_set, 3000, "audioOutputMode Bad Request", "2.0", True),
    ("system/settings/set",'{"audioOutputSource": "HDMI"}', dab.system.settings_set, 3000, "audioOutputSource", "2.0", False),
    ("system/settings/set",'{"audioOutputSource": "invalid"}', dab.system.settings_set, 3000, "audioOutputSource Bad Request", "2.0", True),
    ("system/settings/set",'{"videoInputSource": "HDMI1"}', dab.system.settings_set, 3000, "videoInputSource", "2.0", False),
    ("system/settings/set",'{"videoInputSource": "invalid"}', dab.system.settings_set, 3000, "videoInputSource Bad Request", "2.0", True),
    ("system/settings/set",'{"audioVolume": 10}', dab.system.settings_set, 3000, "audioVolume", "2.0", False),
    ("system/settings/set",'{"audioVolume": 120}', dab.system.settings_set, 3000, "audioVolume - Negative Test", "2.0", True),
    ("system/settings/set",'{"audioVolume": true}', dab.system.settings_set, 3000, "audioVolume bad request", "2.0", True),
    ("system/settings/set",'{"mute": false}', dab.system.settings_set, 3000, "mute", "2.0", False),
    ("system/settings/set",'{"mute": "invalid"}', dab.system.settings_set, 3000, "mute bad request", "2.0", True),
    ("system/settings/set",'{"textToSpeech": true}', dab.system.settings_set, 3000, "textToSpeech", "2.0", False),
    ("system/settings/set",'{"textToSpeech": "invalid"}', dab.system.settings_set, 3000, "textToSpeech bad request", "2.0", True),
    ("system/settings/set", '{"screenSaver": true}', dab.system.settings_set, 5000, "Set Screen Saver", "2.1", False),
    ("system/settings/set", '{"screenSaverTimeout": 300}', dab.system.settings_set, 5000, "Set Screen Saver Timeout", "2.1", False ),
    ("system/settings/set", '{"screenSaverMinTimeout": 60}', dab.system.settings_set, 5000, "Set Screen Saver Min Timeout", "2.1", False),
    ("system/settings/set", '{"personalizedAds": true}', dab.system.settings_set, 5000, "Set Personalized Ads", "2.1" , False),
    ("system/settings/set", '{"highContrastText": true}', dab.system.settings_set, 5000, "Set High Contrast Text", "2.1" , False),
    ("system/settings/set", '{"identifierForAdvertising": true}', dab.system.settings_set, 5000, "Set identifier For Advertising", "2.1" , False),
    ("system/settings/set", '{"brightness": 10}', dab.system.settings_set, 5000, "Set brightness", "2.1" , False),
    ("system/settings/set", '{"contrast": 10}', dab.system.settings_set, 5000, "Set contrast", "2.1" , False),
    ("system/settings/set", '{"timeZone": "America/Los_Angeles"}', dab.system.settings_set, 5000, "Set timeZone", "2.1" , False),
    ("input/key/list",'{}', dab.input.list, 200, "Conformance", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_HOME"}', dab.input.key_press, 1000, "KEY_HOME", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_VOLUME_UP"}', dab.input.key_press, 1000, "KEY_VOLUME_UP", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_VOLUME_DOWN"}', dab.input.key_press, 1000, "KEY_VOLUME_DOWN", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_MUTE"}', dab.input.key_press, 1000, "KEY_MUTE", "2.0", False),
    ("input/key-press",'{"keyCode": "dummy"}', dab.input.key_press, 1000, "dummy", "2.0", True),
    ("input/key-press",'{"keyCode": ""}', dab.input.key_press, 1000, "null", "2.0", True),
    ("input/key-press",'{"keyCode": "KEY_CHANNEL_UP"}', dab.input.key_press, 1000, "KEY_CHANNEL_UP", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_CHANNEL_DOWN"}', dab.input.key_press, 1000, "KEY_CHANNEL_DOWN", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_MENU"}', dab.input.key_press, 1000, "KEY_MENU", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_EXIT"}', dab.input.key_press, 1000, "KEY_EXIT", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_INFO"}', dab.input.key_press, 1000, "KEY_INFO", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_GUIDE"}', dab.input.key_press, 1000, "KEY_GUIDE", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_CAPTIONS"}', dab.input.key_press, 1000, "KEY_CAPTIONS", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_UP"}', dab.input.key_press, 1000, "KEY_UP", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_PAGE_UP"}', dab.input.key_press, 1000, "KEY_PAGE_UP", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_PAGE_DOWN"}', dab.input.key_press, 1000, "KEY_PAGE_DOWN", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_RIGHT"}', dab.input.key_press, 1000, "KEY_RIGHT", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_DOWN"}', dab.input.key_press, 1000, "KEY_DOWN", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_LEFT"}', dab.input.key_press, 1000, "KEY_LEFT", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_ENTER"}', dab.input.key_press, 1000, "KEY_ENTER", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_BACK"}', dab.input.key_press, 1000, "KEY_BACK", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_PLAY"}', dab.input.key_press, 1000, "KEY_PLAY", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_PLAY_PAUSE"}', dab.input.key_press, 1000, "KEY_PLAY_PAUSE", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_PAUSE"}', dab.input.key_press, 1000, "KEY_PAUSE", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_STOP"}', dab.input.key_press, 1000, "KEY_STOP", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_REWIND"}', dab.input.key_press, 1000, "KEY_REWIND", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_FAST_FORWARD"}', dab.input.key_press, 1000, "KEY_FAST_FORWARD", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_SKIP_REWIND"}', dab.input.key_press, 1000, "KEY_SKIP_REWIND", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_SKIP_FAST_FORWARD"}', dab.input.key_press, 1000, "KEY_SKIP_FAST_FORWARD", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_0"}', dab.input.key_press, 1000, "KEY_0", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_1"}', dab.input.key_press, 1000, "KEY_1", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_2"}', dab.input.key_press, 1000, "KEY_2", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_3"}', dab.input.key_press, 1000, "KEY_3", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_4"}', dab.input.key_press, 1000, "KEY_4", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_5"}', dab.input.key_press, 1000, "KEY_5", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_6"}', dab.input.key_press, 1000, "KEY_6", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_7"}', dab.input.key_press, 1000, "KEY_7", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_8"}', dab.input.key_press, 1000, "KEY_8", "2.0", False),
    ("input/key-press",'{"keyCode": "KEY_9"}', dab.input.key_press, 1000, "KEY_9", "2.0", False),
    ("input/key-press", '{"keyCode": "KEY_RED"}', dab.input.key_press, 1000, "KEY_RED", "2.0", False),
    ("input/key-press", '{"keyCode": "KEY_GREEN"}', dab.input.key_press, 1000, "KEY_GREEN", "2.0", False),
    ("input/key-press", '{"keyCode": "KEY_YELLOW"}', dab.input.key_press, 1000, "KEY_YELLOW", "2.0", False),
    ("input/key-press", '{"keyCode": "KEY_BLUE"}', dab.input.key_press, 1000, "KEY_BLUE", "2.0", False),
    ("input/key-press", '{"keyCode": "KEY_YOUTUBE"}', dab.input.key_press, 1000, "KEY_YOUTUBE", "2.0", False),
    ("input/key-press",'{"keyCode_": "KEY_HOME"}', dab.input.key_press, 1000, "KEY_HOME Bad Request1", "2.0", True),
    ("input/key-press",'{"keyCode": "invalid"}', dab.input.key_press, 1000, "KEY_HOME Bad Request2", "2.0", True),
    ("input/key-press",'{"keyCode": true}', dab.input.key_press, 1000, "KEY_HOME Bad Request3", "2.0", True),
    ("input/long-key-press",'{"keyCode": "KEY_HOME", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_HOME", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_VOLUME_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_VOLUME_UP", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_VOLUME_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_VOLUME_DOWN", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_MUTE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_MUTE", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_CHANNEL_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CHANNEL_UP", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_CHANNEL_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CHANNEL_DOWN", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_MENU", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_MENU", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_EXIT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_EXIT", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_INFO", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_INFO", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_GUIDE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_GUIDE", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_CAPTIONS", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_CAPTIONS", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_UP", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_PAGE_UP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAGE_UP", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_PAGE_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAGE_DOWN", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_RIGHT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_RIGHT", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_DOWN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_DOWN", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_LEFT", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_LEFT", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_ENTER", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_ENTER", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_BACK", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_BACK", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_PLAY", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PLAY", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_PLAY_PAUSE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PLAY_PAUSE", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_PAUSE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_PAUSE", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_STOP", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_STOP", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_REWIND", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_REWIND", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_FAST_FORWARD", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_FAST_FORWARD", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_SKIP_REWIND", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_SKIP_REWIND", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_SKIP_FAST_FORWARD", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_SKIP_FAST_FORWARD", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_0", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_0", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_1", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_1", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_2", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_2", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_3", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_3", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_4", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_4", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_5", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_5", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_6", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_6", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_7", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_7", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_8", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_8", "2.0", False),
    ("input/long-key-press",'{"keyCode": "KEY_9", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_9", "2.0", False),
    ("input/long-key-press", '{"keyCode": "KEY_RED", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_RED", "2.0", False),
    ("input/long-key-press", '{"keyCode": "KEY_GREEN", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_GREEN", "2.0", False),
    ("input/long-key-press", '{"keyCode": "KEY_YELLOW", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_YELLOW", "2.0", False),
    ("input/long-key-press", '{"keyCode": "KEY_BLUE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_BLUE", "2.0", False),
    ("input/long-key-press", '{"keyCode": "KEY_YOUTUBE", "durationMs": 3000}', dab.input.long_key_press, 3200, "KEY_YOUTUBE", "2.0", False),
    ("output/image",'{}', dab.output.image, 2000, "Conformance", "2.0", False),
    ("device-telemetry/start",'{"duration": 1000}', dab.device_telemetry.start, 700, "Conformance", "2.0", False),
    ("device-telemetry/stop",'{}', dab.device_telemetry.stop, 200, "Conformance", "2.0", False),
    ("app-telemetry/start",lambda: f'{{"appId": "{config.apps["youtube"]}", "duration": 1000}}', dab.app_telemetry.start, 700, "Conformance", "2.0", False),
    ("app-telemetry/stop",lambda: f'{{"appId": "{config.apps["youtube"]}"}}', dab.app_telemetry.stop, 200, "Conformance", "2.0", False),
    ("health-check/get",'{}', dab.health_check.get, 2000, "Conformance", "2.0", False),
    ("voice/list",'{}', dab.voice.list, 200, "Conformance", "2.0", False),
    ("voice/set",f'{{"voiceSystem":{{"name":"{config.va}","enabled":true}}}}', dab.voice.set, 5000, "Conformance", "2.0", False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/ladygaga.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance", "2.0", False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/OpenNetflix.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance Open Netflix", "2.0", False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/OpenNetflix.mp4", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance With Unsupported Format", "2.0", True),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/CorruptedAudio.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000, "Conformance With Corrupted Audio", "2.0", True),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/KoreanAudio.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000,"Sending Different Language Audio", "2.0",False),
    ("voice/send-audio",f'{{"fileLocation": "https://storage.googleapis.com/ytlr-cert.appspot.com/voice/LongAudioClip.wav", "voiceSystem": "{config.va}"}}',dab.voice.send_audio, 10000,"Sending Long Audio Clip", "2.0",False),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA", "2.0", False),
    ("voice/send-text",f'{{"requestText_" : "Play lady Gaga music on YouTube", "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request1", "2.0", True),
    ("voice/send-text",f'{{"requestText" : true, "voiceSystem": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request2", "2.0", True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem_": "{config.va}"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request3", "2.0", True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": "invalid"}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request4", "2.0", True),
    ("voice/send-text",f'{{"requestText" : "Play lady Gaga music on YouTube", "voiceSystem": true}}', dab.voice.send_text, 10000, "Conformance With VA Bad Request5", "2.0", True),
    ("version",' {}', dab.version.default, 200, "Conformance", "2.0", False),
    ("system/restart",' {}', dab.system.restart, 30000, "Conformance", "2.0", False),
    ("applications/install", lambda: json.dumps({"fileLocation": f"file://{ensure_app_available()}"}), dab.applications.install, 120000, "Install App Conformance", "2.1", False), 
    ("applications/install", lambda: json.dumps({"fileLocation": f""}), dab.applications.install, 120000, "Install App Conformance With Blank URL", "2.1", True),
    ("applications/install", lambda: json.dumps({"fileLocation": f"file://{ensure_app_available('unsupported_format_app.txt')}"}), dab.applications.install, 120000, "Install App Conformance With Incorrect Format", "2.1", True),

    ("applications/uninstall",lambda: f'{{"appId": "{config.apps["sample_app"]}"}}', dab.applications.uninstall, 50000, "Conformance", "2.1", False),
    ("applications/uninstall",lambda: f'{{"appId": "com.example!@#"}}', dab.applications.uninstall, 50000, "Conformance Bad Request", "2.1", True),
    ("applications/clear-data",lambda: f'{{"app_url": "{config.apps["sample_app_url"]}"}}', dab.applications.clear_data, 10000, "Conformance", "2.1", False),
    ("applications/clear-data",lambda: f'{{"appId": ""}}', dab.applications.clear_data, 10000, "Conformance Bad Request", "2.1", True),
    ("applications/install-from-app-store", lambda: json.dumps({"appId": get_or_prompt_appstore_url()}), dab.applications.install_from_appstore, 120000, "Install App Conformance", "2.1" , False),
    ("system/logs/start-collection", '{}', dab.system.start_log_collection, 200, "Conformance", "2.1" , False), 
    ("system/logs/stop-collection", '{}', dab.system.stop_log_collection, 200, "Conformance", "2.1" , False), 
    ("system/logs/stop-collection", '{}', dab.system.stop_log_collection, 400, "Stop Without Start Negative", "2.1" , True),
    ("content/search", '{"searchText": "home"}', dab.content.search, 200, "Conformance", "2.1" , False),
    ("content/search", '{"searchText": ""}', dab.content.search, 200, "Conformance Bad Request", "2.1" , True),
    ("content/recommendations", '{}', dab.content.recommendations, 200, "Conformance", "2.1" , False),
    ("content/open", '{"entryId": "b8884dfa-60e8-448a-99f3-bcf283dcc903"}', dab.content.open, 200, "Conformance", "2.1" , False),
    ("system/power-mode/get", '{}', dab.system.power_mode_get, 200, "Conformance", "2.1" , False),
    ("system/power-mode/set", '{"powerMode": "Standby"}', dab.system.power_mode_set, 200, "Conformance", "2.1" , False),
    ("system/power-mode/set", '{"powerMode": "invalid"}', dab.system.power_mode_set, 200, "Conformance Bad Request", "2.1" , True),
    ("system/setup/skip", '{}', dab.system.setup_skip, 1000, "Conformance", "2.1" , False),
]
