name: Update Test Version on Main Push

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 8-digit Test Version
        run: |
          DATE=$(date +'%y%m%d')
          VERSION_FILE="test_version.txt"
          if [ -f "$VERSION_FILE" ]; then
            LAST_VERSION=$(cat $VERSION_FILE)
            LAST_DATE=${LAST_VERSION:0:6}
            LAST_COUNT=${LAST_VERSION:6:2}
            if [ "$LAST_DATE" = "$DATE" ]; then
              COUNT=$(printf "%02d" $((10#$LAST_COUNT + 1)))
              VERSION="${DATE}${COUNT}"
            else
              VERSION="${DATE}01"
            fi
          else
            VERSION="${DATE}01"
          fi
          echo $VERSION > $VERSION_FILE

      - name: Commit & Push Test Version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test_version.txt
          git commit -m "chore: update test version to $(cat test_version.txt)" || echo "No changes to commit"
          git push

